/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./../src/components/Contact/index.vue')['default']
    Container: typeof import('./../src/components/Container/index.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    Footer: typeof import('./../src/components/Footer/index.vue')['default']
    Header: typeof import('./../src/components/Header/index.vue')['default']
    Info: typeof import('./../src/components/Info/index.vue')['default']
    Mission: typeof import('./../src/components/Mission/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Team: typeof import('./../src/components/Team/index.vue')['default']
  }
}
